### ISSUE TITLE
Keys starting with dynamic command names will be wrongfully replaced

### ISSUE THREAD

**Issue by Friend2868** [Stone-Red-Code/ClipCMD#3]
**Describe the bug**
When having a key like datetimevalue it will get replaced by 15/12.

**To Reproduce**
write <prefix>datetimevalue <suffix>
copy it
it gets replaced by <date>

**Expected behavior**
The static key defined should show up

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10: version 0.2

**Comment by Stone-Red-Code** [comment]
Fixed
